sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3c7273990340_key -iv $encrypted_3c7273990340_iv -in secretenv_test.enc -out secretenv_test -d
- ./build.sh test
- ./run.sh
- rm Gemfile
script:
  - docker exec 4min-faith rake
